language: python

python:
  - "3.6"
  - "3.6-dev"
  
install: 
  - pip install -r requirements.txt
  - pip install coveralls
  
script:
  - pytest

after script:
  - coveralls

after success:
  - codecov
